"""initial migration: customers payment_events recovery_cases execution_logs

Revision ID: cf7f3c678a8e
Revises: 
Create Date: 2026-08-21 21:23:16.373482
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf7f3c678a8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('lifetime_value_paise', sa.BigInteger(), nullable=False),
    sa.Column('historical_success_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('external_payment_id', sa.String(length=255), nullable=True),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('error_description', sa.String(length=1024), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_event_id', name='uq_payment_events_external_event_id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index('ix_payment_events_external_order_id', 'payment_events', ['external_order_id'], unique=False)
    op.create_index('ix_payment_events_external_payment_id', 'payment_events', ['external_payment_id'], unique=False)
    op.create_index('ix_payment_events_payload_hash', 'payment_events', ['payload_hash'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_category', sa.String(length=32), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommended_strategy', sa.String(length=32), nullable=True),
    sa.Column('expected_value_paise', sa.BigInteger(), nullable=True),
    sa.Column('decision_audit_trail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_human', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(recovery_probability IS NULL) OR (recovery_probability >= 0 AND recovery_probability <= 1)', name='ck_recovery_cases_probability_range'),
    sa.CheckConstraint('retry_count >= 0', name='ck_recovery_cases_retry_count_non_negative'),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_event_id')
    )
    op.create_index('ix_recovery_cases_next_run_at', 'recovery_cases', ['next_run_at'], unique=False)
    op.create_index('ix_recovery_cases_status', 'recovery_cases', ['status'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_execution_logs_idempotency_key', 'execution_logs', ['idempotency_key'], unique=True)
    op.create_index('ix_execution_logs_status', 'execution_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_logs_status', table_name='execution_logs')
    op.drop_index('ix_execution_logs_idempotency_key', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_recovery_cases_status', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_next_run_at', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index('ix_payment_events_payload_hash', table_name='payment_events')
    op.drop_index('ix_payment_events_external_payment_id', table_name='payment_events')
    op.drop_index('ix_payment_events_external_order_id', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_table('customers')
    # ### end Alembic commands ###
